/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package layout;

import java.awt.CardLayout;

/**
 *
 * @author Asus
 */
public class PenampilGambarComboBox extends javax.swing.JFrame {

    /**
     * Creates new form PenampilGambarComboBox
     */
    public PenampilGambarComboBox() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboboxPanel = new javax.swing.JPanel();
        imageCB = new javax.swing.JComboBox<>();
        imagePanel = new javax.swing.JPanel();
        classyLB = new javax.swing.JLabel();
        streetwareLB = new javax.swing.JLabel();
        gorpcoreLB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        imageCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CLASSY", "STREETWARE", "GORPCORE" }));
        imageCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageCBActionPerformed(evt);
            }
        });
        comboboxPanel.add(imageCB);

        getContentPane().add(comboboxPanel, java.awt.BorderLayout.PAGE_START);

        imagePanel.setLayout(new java.awt.CardLayout());

        classyLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        classyLB.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\OneDrive\\Pictures\\classy - Copy.jpg")); // NOI18N
        imagePanel.add(classyLB, "0");

        streetwareLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        streetwareLB.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\OneDrive\\Pictures\\streetware - Copy.JPG")); // NOI18N
        imagePanel.add(streetwareLB, "1");

        gorpcoreLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gorpcoreLB.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\OneDrive\\Pictures\\gorpcore - Copy.jpg")); // NOI18N
        imagePanel.add(gorpcoreLB, "2");

        getContentPane().add(imagePanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imageCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageCBActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) (imagePanel.getLayout());
        cl.show(imagePanel,String.valueOf(imageCB.getSelectedIndex()));
    }//GEN-LAST:event_imageCBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PenampilGambarComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PenampilGambarComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PenampilGambarComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PenampilGambarComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PenampilGambarComboBox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel classyLB;
    private javax.swing.JPanel comboboxPanel;
    private javax.swing.JLabel gorpcoreLB;
    private javax.swing.JComboBox<String> imageCB;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JLabel streetwareLB;
    // End of variables declaration//GEN-END:variables

 
}
